markdown: redcarpet
name: 18F Guides Template
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Acqstack Journeymap
  internal: true
- text: External Clients
  url: external-clients/external-clients/
  internal: true
  children:
  - text: Biz Dev
    url: bizdev/
    internal: true
  - text: Intake
    url: intake/
    internal: true
  - text: Agreements
    url: agreements/
    internal: true
  - text: Staffing
    url: staffing/
    internal: true
  - text: Onboarding
    url: onboarding/
    internal: true
  - text: Solicitation Scoping
    url: solicitation-scoping/
    internal: true
  - text: Solictation Drafting
    url: drafting/
    internal: true
  - text: CO Team Assigned
    url: co-team-assigned/
    internal: true
  - text: Acquisition Package Review
    url: acq-package-review/
    internal: true
  - text: Releasing RFP
    url: release-rfp/
    internal: true
  - text: Question and Answers
    url: qa/
    internal: true
  - text: Proposals
    url: proposals/
    internal: true
  - text: Evaluation
    url: evaluation/
    internal: true
  - text: Award
    url: award/
    internal: true
- text: Internal Clients
  url: internal-clients/
  internal: true
  children:
  - text: Intake
    url: intake/
    internal: true
  - text: Staffing
    url: staffing/
    internal: true
  - text: Onboarding
    url: onboarding/
    internal: true
  - text: Agreements
    url: agreements/
    internal: true
  - text: Solicitation Scoping
    url: solicitation-scoping/
    internal: true
  - text: Infrastructure Review
    url: infrastructure-review/
    internal: true
  - text: Solictation Drafting
    url: drafting/
    internal: true
  - text: CO Team Assigned
    url: co-team-assigned/
    internal: true
  - text: Acquisition Package Review
    url: acq-package-review/
    internal: true
  - text: Releasing RFP
    url: release-rfp/
    internal: true
  - text: Question and Answers
    url: qa/
    internal: true
  - text: Proposals
    url: proposals/
    internal: true
  - text: Evaluation
    url: evaluation/
    internal: true
  - text: Award
    url: award/
    internal: true

repos:
- name: Acqstack Journeymap
  description: acqstack journeymap
  url: https://github.com/18F/acqstack-journeymap

back_link:
  url: "https://pages.18f.gov/guides/"
  text: Read more 18F Guides

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
